---

- hosts: all
#  become: true
  tasks:

  - name: update repository index
    package:
      name:
        - "{{ var_nginx }}"
        - "{{ var_ncdu }}"
        - "{{ var_apache }}"
        - "{{ var_php }}"
        - "{{ var_w3m }}"
      state: latest
      update_cache: yes
