---

- hosts: all
#  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes
 
  - name: remove apache package
    dnf:
      name: httpd
      state: absent

  - name: Install nginx
    dnf:
      name: nginx
      state: absent

  - name: Install w3m
    dnf:
      name: w3m
